- import_tasks: deps.yml
  tags:
    - nginx_deps

- import_tasks: firewalld.yml
  tags:
    - nginx_firewalld
  when:
    - ansible_distribution == 'CentOS'
    - configure_firewall|default(False)|bool

- import_tasks: ufw.yml
  tags:
    - nginx_ufw
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - configure_firewall|default(False)|bool

- import_tasks: nginx.yml
  tags:
    - nginx_config

- import_tasks: vhosts.yml
  tags:
    - vhosts_config
