nginx_image: nginx
nginx_tag: latest
nginx_username: www-data
nginx_shared_mem_rate_limit: 2m
nginx_req_per_sec: 10
vhost_nginx_burst_limit: 25

goshimmer_internal_spammer_port: 8080
goshimmer_external_spammer_port: 18080
goshimmer_internal_dashboard_port: 8081
goshimmer_external_dashboard_port: 18081
